#!/usr/bin/env node
// Builds data/opportunities.js from data/opportunities.json + data/profile.json so the page
// works when opened straight from disk (file://) as well as on GitHub Pages / Netlify.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(join(root, 'data/opportunities.json'), 'utf8'));
const profile = JSON.parse(readFileSync(join(root, 'data/profile.json'), 'utf8'));

const REQUIRED = ['company', 'role_title', 'job_url', 'score', 'region'];
const REGIONS = new Set(['UK', 'Europe', 'Remote', 'US', 'Other']);
const errors = [];
const seen = new Set();
(src.opportunities || []).forEach((o, i) => {
  REQUIRED.forEach((k) => { if (o[k] === undefined || o[k] === null || o[k] === '') errors.push(`#${i} ${o.company || '?'}: missing ${k}`); });
  if (o.id) { if (seen.has(o.id)) errors.push(`#${i}: duplicate id ${o.id}`); seen.add(o.id); }
  if (!REGIONS.has(o.region)) errors.push(`#${i} ${o.company}: region must be one of ${[...REGIONS].join('|')}`);
  if (typeof o.score !== 'number' || o.score < 1 || o.score > 10) errors.push(`#${i} ${o.company}: score must be 1-10`);
  (o.contacts || []).forEach((c, j) => {
    if (!c.name) errors.push(`#${i} ${o.company} contact ${j}: missing name`);
    if (c.linkedin_url && !/^https:\/\/([a-z]{2,3}\.)?linkedin\.com\/in\//i.test(c.linkedin_url)) errors.push(`#${i} ${o.company} contact ${c.name}: linkedin_url is not a profile URL`);
    if (c.email && !['verified_public', 'pattern_guess'].includes(c.email_status)) errors.push(`#${i} ${o.company} contact ${c.name}: email needs email_status verified_public|pattern_guess`);
  });
  ['email_subject', 'email_body', 'linkedin_note', 'linkedin_inmail'].forEach((k) => { if (!(o.drafts && o.drafts[k])) errors.push(`#${i} ${o.company}: missing draft ${k}`); });
});
if (errors.length) { console.error('Data validation failed:\n  ' + errors.join('\n  ')); process.exit(1); }

const out = `// GENERATED by scripts/build-data.mjs — edit data/opportunities.json and rebuild.\n` +
  `window.OH_META = ${JSON.stringify(src.meta || {})};\n` +
  `window.OH_PROFILE = ${JSON.stringify(profile)};\n` +
  `window.OH_DATA = ${JSON.stringify(src.opportunities || [])};\n`;
writeFileSync(join(root, 'data/opportunities.js'), out);
const n = (src.opportunities || []).length;
const c = (src.opportunities || []).reduce((a, o) => a + (o.contacts || []).length, 0);
console.log(`Wrote data/opportunities.js: ${n} opportunities, ${c} contacts`);
